pcsem:sem.cpp
	g++ $^ -o $@	-pthread
sem:sem.c
	gcc $^ -o $@	-pthread
sale_buy:sale_buy.cpp
	g++ $^ -o $@	-pthread
cond:cond.c
	gcc $^ -o $@	-pthread
mutex:mutex.c
	gcc $^ -o $@	-pthread
term:term.c
	gcc $^ -o $@	-pthread
creat:creat.c
	gcc $^ -o $@	-pthread
